flask_blog/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

flask_blog/chatroom/routes.py
from flask import Blueprint, render_template, request
from flask_blog.models import chatHistory, User, chatRoom
from flask_blog import socketio, db
from flask_socketio import send, emit, join_room, leave_room
from flask_login import login_required, current_user
import json
import inspect#adding info
from datetime import datetime

chatroom = Blueprint('chatroom', __name__)


@chatroom.route('/chatroom', methods=['POST', 'GET'])
@login_required
def chatroom_homepage():
    return render_template('chatroom.html')
    

@chatroom.route('/chatroom/history/<string:room_name>')
@login_required
def chatroom_history(room_name):
    chatroom = chatRoom.query.filter_by(room_name=room_name).first()
    messages = chatroom.chatroom_history
    return render_template('history_page.html', room_name=room_name, messages=messages)


socketio.room_users = {}#room:users
socketio.reqid_info = {}#sid{room, talker}
socketio.user_sid = {}#username:sid


@socketio.on('connect')
def connect_event_handler():
    @socketio.on('join')
    def talker_join_handler(data):
        talker = current_user.username
        room = data['room']
        print(room)
        
        chatroom = chatRoom.query.filter_by(room_name=room).first()
        if chatroom is None:
            chatroom = chatRoom(room_name=room)
            db.session.add(chatroom)
            db.session.commit()
        try:
            original_room = socketio.reqid_info[request.sid]['room']
            if room != original_room:
                socketio.room_users[room].remove(talker)
                leave_room(original_room)
        except:
            pass

        susr = f'{talker}--{request.sid}'
        
        #add talker into talker list
        socketio.room_users.setdefault(room, [])
        if talker not in socketio.room_users[room]:
            socketio.room_users[room].append(talker)

        # socketio.room_users.setdefault(room, []).append(susr)#append room if there isn't a room
        socketio.reqid_info.setdefault(request.sid, {}).update({
            'room': room,
            'talker': talker,
        })
        join_room(room)
        current_user.join(chatroom)
        db.session.commit()

        
        message = f'#=>{datetime.now()}:{susr} action:{inspect.stack()[0][-4:-2]} room:{room}'
        print(message)
        talkers = []
        for item_users in socketio.room_users.values():
            if item_users not in talkers:
                talkers.extend(item_users)
        print('#=>current users: ', talkers)
        socketio.emit('sys broadcast', {'message':message})
    
    
    @socketio.on('disconnect')
    def disconnect_handler():
        talker = current_user.username
        room = socketio.reqid_info[request.sid]['room']
        susr = f'{talker}--{request.sid}'
        try:
            socketio.room_users[room].remove(talker)
        except:
            pass
        message = f'#=>{datetime.now()}:{susr} action:{inspect.stack()[0][-4:-2]} room:{room}'
        print(message)
        socketio.emit('sys broadcast', {'message':message})
        leave_room(room)


    @socketio.on('message')
    def message_handler(msg): 

        room = socketio.reqid_info[request.sid]['room']   
        chatroom = chatRoom.query.filter_by(room_name=room).first()

        print('Message: '+ msg)

        message = chatHistory(message=msg, talker=current_user, chatroom_belonged=chatroom)
        db.session.add(message)
        db.session.commit()

        d = {'message_type': 'message', 'message':message.message, 'talker':message.talker.username, 'time':message.time_stamp.strftime(r'%Y-%m-%d %H:%M')}
        d = json.dumps(d)

        send(d, broadcast=True, room=room)


    @socketio.on('get room talkers')
    def online_talkers_handler(room_name):
        chatroom = chatRoom.query.filter_by(room_name=room_name).first()
        talkers = []
        for talker in chatroom.talkers_joined:
            talkers.append(talker.username)
        message = str(socketio.room_users[room_name]) + str(talkers)
        print('users in room: ', message)
        emit('sys broadcast', {'message': 'sys: '+ message})


    @socketio.on('private message', namespace='/private')
    def private_message_handler(payload):
        friend_name = payload['friend_name']
        friend = User.query.filter_by(username=friend_name).first()
        if current_user.is_friend(friend):
            message = payload['private_message']
            if socketio.user_sid[friend_name]:
                firend_sid = socketio.user_sid[friend_name]
                emit('new private message', message, room=firend_sid)
            else:
                pass
        else:
            emit('sys broadcast', {'message': 'sys: '+ f'{friend_name} is still not your friend!'})

        

flask_blog/main/routes.py
from flask import render_template, request, Blueprint
from flask_blog.models import Post
from flask_login import login_required, current_user


main = Blueprint('main', __name__)


@main.route("/home")
@login_required
def home():
    page = request.args.get('page', 1, type=int)
    posts = current_user.followed_posts().paginate(page=page, per_page=5)
    return render_template('home.html', posts=posts)


@main.route("/")
@main.route('/everyone')
def home_everyone():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('home.html', posts=posts)



@main.route("/about")
def about():
    return render_template('about.html', title='About')

flask_blog/posts/routes.py
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint
from flask_login import current_user, login_required
from flask_blog import db
from flask_blog.models import Post
from flask_blog.posts.forms import PostForm
from markdown import markdown

posts = Blueprint('posts', __name__)


@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data,
                    content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!', 'success')
        return redirect(url_for('main.home'))
    return render_template('create_post.html', title='New Post', form=form, legend='New Post')


@posts.route("/post/<int:post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)


@posts.route("/post/<int:post_id>/update", methods=['POST', 'GET'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your post has been updated!', 'success')
        return redirect(url_for('posts.post', post_id = post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html', title='Update Post', form=form, legend='Update Post')


@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted', 'info')
    return redirect(url_for('main.home'))

flask_blog/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from flask_blog import db, bcrypt
from flask_blog.models import User, Post, Notification
from flask_blog.users.forms import RegistrationForm, LoginForm, UpdateAccountField, RequestResetForm, ResetPasswordForm
from flask_blog.users.utils import save_picture, send_reset_email, delete_picture


users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        flash(
            f'You have already logged in! Welcome back user: {current_user.username} XD!', 'info')
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(
            form.password.data).decode('utf-8')
        user = User(username=form.username.data,
                    password=hashed_password, email=form.email.data)
        db.session.add(user)
        db.session.commit()
        flash(f"Your account has been created! You are now able to log in.", 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['POST', 'GET'])
def login():
    if current_user.is_authenticated:
        flash(
            f'You have already logged in! Welcome back user: {current_user.username} XD!', 'info')
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash(f"Login Unsuccessful! Please check email or password!", 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route('/logout')
def logout():
    logout_user()
    flash(f'Successfully logged out! See ya!', 'primary')
    return redirect(url_for('main.home'))

@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountField()
    if form.validate_on_submit():

        if form.picture.data:
            original_picture = current_user.image_file
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
            delete_picture(original_picture)
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for(
        'static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account', image_file=image_file, form=form)

@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user).order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('user_posts.html', posts=posts, user=user)


@users.route("/reset_password", methods=['POST', 'GET'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title="Reset Password", form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid token!', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data)
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You can login with your new password!', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)


@users.route("/user/follow/<username>")
@login_required
def follow(username):
    user = User.query.filter_by(username=username).first()
    if user is None:
        flash(f'User {username} does not exist!', 'warning')
        return redirect(url_for('main.home'))
    if user == current_user:
        flash('You cannot follow yourself!', 'warning')
        return redirect(url_for('users.account'))
    else:
        current_user.follow(user)
        flash(f'You are now following {username}!', 'info')
        friend_invitation = Notification(sender_name=current_user.username, receiver_name=username, 
            content=f"User {current_user.username} has followed you! Follow him/her so that you can chat and share posts with him/her!")
        db.session.add(friend_invitation)
        db.session.commit()
        return redirect(url_for('users.user_posts', username=username))


@users.route("/user/unfollow/<username>")
@login_required
def unfollow(username):
    user = User.query.filter_by(username=username).first()
    if user is None:
        flash(f'User {username} does not exist!', 'warning')
        return redirect(url_for('main.home'))
    if user == current_user:
        flash('You cannot unfollow yourself!')
        return redirect(url_for('account'))
    else:
        current_user.unfollow(user)
        db.session.commit()
        flash(f'You are not following {username}!', 'info')
        friend_denial = Notification(sender_name=current_user.username, receiver_name=username,
            content=f"User {current_user.username} has unfollowed you. You can no longer chat with him. You can also choose to unfollow him/her.")
        db.session.commit()
        return redirect(url_for('users.user_posts', username=username))


@users.route("/user/notifications")
@login_required
def notifications():
    notifications = Notification.query.filter_by(receiver_name=current_user.username).all()
    return render_template('notifications.html', notifications=notifications)

flask_blog/templates/about.html
{% extends "layout.html" %}
{% block content %}
    <h1>About Page</h1>
{% endblock content %}

flask_blog/templates/account.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <div class="media">
        <img class="rounded-circle account-img" src="{{ image_file }}">
        <div class="media-body">
            <h2 class="account-heading">{{ current_user.username }}</h2>
            <p class="text-secondary">{{ current_user.email }}</p>
        </div>
    </div>

    <form method="POST" action="" , enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Account Info</legend>
            <div class="form-group">
                {{ form.username.label(class="form-control-label") }}
                {% if form.username.errors %}
                {{ form.username(class="form-control is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.username.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.username(class="form-control") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                {% if form.email.errors %}
                {{ form.email(class="form-control is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.email(class="form-control") }}
                {% endif %}
            </div>

            <div class="form-group">
                {{ form.picture.label() }}
                {{ form.picture(class = "form-control-file") }}
                {% if form.picture.errors %}
                {% for error in form.picture.errors %}
                <span class="text-danger">{{ error }}</span><br>
                {% endfor %}
                {% endif %}
            </div>

            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>

        </fieldset>
    </form>
</div>
{% endblock content %}

flask_blog/templates/chatroom.html
{% extends 'layout.html' %}
{% block content %}
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/1.4.8/socket.io.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>

<h2>chatroom</h2>
<h3 id="currentRoom">Default room: room0</h3>

<script type="text/javascript">
    $(document).ready(function () {


        var socket = io.connect('http://127.0.0.1:5000');
        var roomName = 'room0';
        

        socket.on('connect', function () {
            socket.emit('join', {'room': 'room0'});
            $('#currentRoom').text('current room: '+roomName);
            $('#systemInfo').append('<li>sys: you have connected!</li>')
        })


        socket.on('sys broadcast', function(sys_message){
            $('#systemInfo').append('<li>' + sys_message['message'] + '</li>');
        })


        socket.on('message', function (message) {
            var message = JSON.parse(message);

            $("#messages").append('<li>' +" " + message['talker'] + ': ' + message['time'] + '  ' + message['message'] + '</li>');
            talker = message['talker'];
            console.log('Received the message');

        })

        $('#sendButton').on('click', function () {
            socket.send($('#myMessage').val());
            $('#myMessage').val('');
        })

        $('#room').on('click', function(){
            roomName = $('#roomName').val();
            alert(roomName);
            socket.emit('join', {'room': $('#roomName').val()});
            $('#currentRoom').text('current room: '+roomName);
        })



        $('#btnAllRoomTalkers').on('click', function(){
            socket.emit('get room talkers', roomName);
        })


        var private_socket = io.connect('http://127.0.0.1:5000/private')

        $('#btnPrivateSend').on('click', function(){
            var friendName = $('#friendName').val();
            var privateMessage = $('#privateMessage').val();
            private_socket.emit('private message', {'friend_name':friendName, 'private_message':privateMessage});
        })

        private_socket.on('new private message', function(msg){
            alert("you have a new private message:"+msg);
        })



    })
</script>
<ul id="messages"></ul>


<input type="text" id="myMessage">
<button id="sendButton">Send</button>
<br>
<input type="text" id="roomName">
<button id="room">Join Room</button>
<br>

<br>
Sent to: <input type="text" id="friendName">
Private Message: <input type="text" id="privateMessage">
<button id="btnPrivateSend">Send to Your Friend</button>

<button id="btnAllRoomTalkers">All Talkers</button>

<h3>systemInfo</h3>
<ul id="systemInfo"></ul>

{% endblock content %}

flask_blog/templates/history_page.html
{% extends "layout.html" %}
{% block content %}
<h2>{{ room_name }}</h2>
<li>
    {% for msg in messages %}
        <ul>{{ msg.message }} at {{ msg.time_stamp }} by {{ msg.talker.username }}</ul>
    {% endfor %}
</li>
{% endblock content %}

flask_blog/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <link rel="stylesheet" tupe="text/css" href="{{ url_for('static', filename = 'main.css') }}">

    {% if title %}
    <title>Flask Blog - {{ title }}</title>
    {% else %}
    <title>Flask Blog</title>
    {% endif %}


</head>

<!-- navigation bar -->
<body>
    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
            <div class="container">
                <a class="navbar-brand mr-4" href="/">Flask Blog</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
                    aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarToggle">
                    <div class="navbar-nav mr-auto">
                        <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
                        <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
                    </div>
                    <!-- Navbar Right Side -->
                    <div class="navbar-nav">
                        {% if current_user.is_authenticated %}
                            <a class="nav-item nav-link" href="{{ url_for('posts.new_post') }}">New Post</a>
                            <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
                            <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                        {% else %}
                            <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                            <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
                        {% endif %} 
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <!-- end of navigation bar -->

    <!-- flash massages -->
    <main role="main" class="container">
        <div class="row">
            <div class="col-md-9">
                {% with messages = get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                        {% for category, message in messages %}
                            <div class="alert alert-{{ category }}">
                                {{ message }}
                            </div>
                        {% endfor %}
                    {% endif %}
                {% endwith %}
                {% block content %}{% endblock content %}
                {% block js %}{% endblock js %}
            </div>
            <!-- end of flash messages -->

            <!-- side bar -->
            <div class="col-md-3">
                <div class="content-section">
                    <h3>Sidebar</h3>
                    <p class='text-muted'>You can put any information here you'd like.
                        <ul class="list-group">
                            <li class="list-group-item list-group-item-light">La qui Posts</li>
                            <li class="list-group-item list-group-item-light">Announcements</li>
                            <li class="list-group-item list-group-item-light">Calendars</li>
                            <li class="list-group-item list-group-item-light">etc</li>
                        </ul>
                    </p>
                    <footer>
                        <small class="text-center">
                        <p class="text-muted"><i>To do something interesting<br>To achieve something great<i><br>You can contact the author via <a href="mailto:tctco2018@gmail.com">tctco2018@gmail.com</a>.</p>
                        </small>
                    </footer>

                </div>
            </div>
            <!-- end of side bar -->
        </div>
    </main>



    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
    

</body>

</html>

flask_blog/templates/login.html
{% extends "layout.html" %}
{% block content %}
<div class="contain-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb4">Log In</legend>
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                {% if form.email.errors %}
                {{ form.email(class="form-control is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.email(class="form-control") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                {% if form.password.errors %}
                {{ form.password(class="form-control is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.password(class="form-control") }}
                {% endif %}
            </div>
            <div class="form-check">
                {{ form.remember(class="form-check-input") }}
                {{ form.remember.label(class="form-check-label") }}
            </div>
            <div class="form-group pt-3">
                {{ form.submit(class="btn btn-outline-info") }}
                <small class="text-muted">
                    <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
                </small>
            </div>           
        </fieldset>
    </form>
</div>
<div class="border-top pt-3 pb-2">
    <small class="text-muted">
        Need An Account?<a href="{{url_for('users.register')}}" class="ml-2">Sign Up</a>
    </small>
</div>

{% endblock %}

flask_blog/templates/notifications.html
{% extends "layout.html" %}
{% block content %}
<h2>Notification page</h2>
<ul>
    {% for notification in notifications %}
        <li>{{ notification.sender_name }}: {{ notification.content }}<br>at: {{ notification.time_stamp }}<br></li>
    {% endfor %}
</ul>
{% endblock content %}

flask_blog/templates/post.html
{% extends "layout.html" %}
{% block content %}
<article class="media content-section">
    <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}" alt="">
    <div class="media-body">
        <div class="article-metadata">
            <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
            <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
            {% if post.author == current_user %}
                <div>
                    <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
                    <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
                </div>
            {% endif %}
        </div>
        <h2 class="article-title">{{ post.title }}</h2>
        <div id="editormd-view">
            <textarea style="display:none;" name="test-editormd-markdown-doc">{{post.content}}</textarea>               
        </div>
    </div>
</article>

<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
              <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}


{% block js %}
<link href="{{ url_for('static', filename='editormd/css/editormd.preview.min.css') }}" rel="stylesheet" />  
<link href="{{ url_for('static', filename='editormd/css/editormd.css') }}" rel="stylesheet" /> 

<script src="{{ url_for('static',filename='editormd/js/jquery.min.js') }}"></script>
<script src="{{ url_for('static', filename='editormd/lib/marked.min.js') }}"></script>
<script src="{{ url_for('static', filename='editormd/lib/prettify.min.js') }}"></script>
<script src="{{ url_for('static', filename='editormd/lib/raphael.min.js') }}"></script>
<script src="{{ url_for('static', filename='editormd/lib/underscore.min.js') }}"></script>
<script src="{{ url_for('static', filename='editormd/lib/marked.min.js') }}"></script>
<script src="{{ url_for('static', filename='editormd/lib/sequence-diagram.min.js') }}"></script>
<script src="{{ url_for('static', filename='editormd/lib/flowchart.min.js') }}"></script>
<script src="{{ url_for('static', filename='editormd/lib/jquery.flowchart.min.js') }}"></script>
<script src="{{ url_for('static', filename='editormd/editormd.js') }}"></script>
<script type="text/javascript">
testEditormdView2 = editormd.markdownToHTML("editormd-view", {
htmlDecode      : "style,script,iframe",  // you can filter tags decode
emoji           : true,
taskList        : true,
tex             : true,  // 默认不解析
flowChart       : true,  // 默认不解析
sequenceDiagram : true,  // 默认不解析
});
</script>
{% endblock js %}